### ISSUE TITLE
Dragula causes runtime error in Angular 2 lastest version 2.4.3.

### ISSUE THREAD

**Issue by BBaysinger** [bevacqua/dragula#460]
The error I get is:

```
Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:38711:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:38845:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:21372:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:21337:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:21112:28)
    at http://localhost:4200/main.bundle.js:21181:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:21174:44)
    at http://localhost:4200/main.bundle.js:21162:50
    at Array.forEach (native)

```

It also doesn't work in Angular 2.1.2, but it _does_ work in v2.2.3.

Is there any fix for this?

**Comment by BBaysinger** [comment]
This issue is here in error. Closing
